### PR TITLE
Supports getting an image from files, and tries to reuse its name

### PR DESCRIPTION
**Pull request by soywiz**
Partial work on https://github.com/holgerbrandl/pasteimages/issues/2

### CODE REVIEW

**Comment by soywiz** [comment]
Couldn't test it because it doesn't work on my M1 machine. I have other bumps to get it working, but this PR doesn't include them.

**Comment by soywiz** [comment]
I have several extra proposals if you are open to some:
* Add .github actions CI support
* Bump versions so it works on Apple M1 machines
* Migrate it to Kotlin so the code is simpler

**Comment by holgerbrandl** [comment]
Thanks for this great addition. All proposals are fine with me. In particular, after being a speaker at this year's Kotlin conf. Shall I wait with the merge then? Or do you want to so this via a separate PR?

**Comment by soywiz** [comment]
@holgerbrandl Nice! Feel free to merge it and I will make other/s PR/s.

**Pull request merged**
